apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: {{ include "techbleat.namespace" . }}
  labels:
    {{- include "techbleat.labels" . | nindent 4 }}
    tier: backend
    app.kubernetes.io/component: user-service
data:
  FRONTEND_ORIGIN: {{ .Values.config.frontendOrigin | quote }}
