apiVersion: v1
kind: Secret
metadata:
  name: activity-service-secret
  namespace: {{ include "techbleat.namespace" . }}
  labels:
    {{- include "techbleat.labels" . | nindent 4 }}
    tier: backend
    app.kubernetes.io/component: activity-service
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgresql://%s:%s@postgres:%v/%s" .Values.postgres.username .Values.postgres.password .Values.postgres.service.port .Values.postgres.database | quote }}
