apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
  namespace: {{ include "techbleat.namespace" . }}
  labels:
    {{- include "techbleat.labels" . | nindent 4 }}
    tier: backend
    app.kubernetes.io/component: transaction-service
data:
  FRONTEND_ORIGIN: {{ .Values.config.frontendOrigin | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.config.springJpaHibernateDdlAuto | quote }}
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  REDIS_HOST: "redis"
  REDIS_PORT: {{ .Values.redis.service.port | quote }}
  SERVER_PORT: {{ .Values.transactionService.service.port | quote }}
