apiVersion: v1
kind: Secret
metadata:
  name: transaction-service-secret
  namespace: {{ include "techbleat.namespace" . }}
  labels:
    {{- include "techbleat.labels" . | nindent 4 }}
    tier: backend
    app.kubernetes.io/component: transaction-service
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://postgres:%v/%s" .Values.postgres.service.port .Values.postgres.database | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password | quote }}
