apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: {{ include "techbleat.namespace" . }}
  labels:
    {{- include "techbleat.labels" . | nindent 4 }}
    tier: backend
    app.kubernetes.io/component: transaction-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.transactionService.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/component: transaction-service
    {{- include "techbleat.selectorLabels" . | nindent 4 }}
