{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "techbleat.serviceAccountName" . }}
  namespace: {{ include "techbleat.namespace" . }}
  labels:
    {{- include "techbleat.labels" . | nindent 4 }}
{{- end }}
